def multinews_setting(args):
    args.batch_size = getattr(args, 'batch_size', 1)
    args.epoch = getattr(args, 'epoch', 100)
    args.report_freq = getattr(args, "report_freq", 50)
    args.accumulate_step = getattr(args, "accumulate_step", 16)
    args.pretrained = getattr(args, "pretrained", None)
    args.model_type = getattr(args, "model_type", "/apdcephfs_qy3/share_1565115/jonxie/model_base/bart-base")
    args.dataset_name = getattr(args, "dataset_name", "/apdcephfs_qy3/share_1565115/jonxie/data_base/SimCAS/multinews_bart_512")
    args.warmup_steps = getattr(args, "warmup_steps", 6400)
    args.grad_norm = getattr(args, "grad_norm", 0)
    args.seed = getattr(args, "seed", 777)
    args.max_lr = getattr(args, "max_lr", 8e-3)
    args.max_len = getattr(args, "max_len", 128)
    args.smooth = getattr(args, "smooth", 0.1)
    args.max_input_len = getattr(args, 'max_input_len', 16384)
    args.max_output_len = getattr(args, 'max_output_len', 1024)
    args.chunk_len = getattr(args, 'chunk_len', 512)
    args.gen_max_len = getattr(args, "gen_max_len", 400)
    args.gen_min_len = getattr(args, "gen_min_len", 150)
    args.length_penalty = getattr(args, "length_penalty", 2.0)
    args.eval_interval = getattr(args, "eval_interval", 1000)
    args.save_interval = getattr(args, "save_interval", 10000)
    args.num_beams = getattr(args, "num_beams", 4)
    args.project_name = getattr(args, "project_name", "bart (simcas-multinews)")
    args.desc = getattr(args, 'desc', 'TODO')
    args.is_wandb = getattr(args, 'is_wandb', False)


def wcep_setting(args):
    args.batch_size = getattr(args, 'batch_size', 1)
    args.epoch = getattr(args, 'epoch', 100)
    args.report_freq = getattr(args, "report_freq", 100)
    args.accumulate_step = getattr(args, "accumulate_step", 8)
    args.pretrained = getattr(args, "pretrained", None)
    args.model_type = getattr(args, "model_type", "/apdcephfs_qy3/share_1565115/jonxie/model_base/bart-base")
    args.dataset_name = getattr(args, "dataset_name", "/apdcephfs_qy3/share_1565115/jonxie/data_base/SimCAS/wcep_bart_512")
    args.warmup_steps = getattr(args, "warmup_steps", 1600)
    args.grad_norm = getattr(args, "grad_norm", 0)
    args.seed = getattr(args, "seed", 970913)
    args.max_lr = getattr(args, "max_lr", 4e-3)
    args.max_len = getattr(args, "max_len", 128)
    args.smooth = getattr(args, "smooth", 0.1)
    args.max_input_len = getattr(args, 'max_input_len', 16384)
    args.max_output_len = getattr(args, 'max_output_len', 1024)
    args.chunk_len = getattr(args, 'chunk_len', 512)
    args.gen_max_len = getattr(args, "gen_max_len", 40)
    args.gen_min_len = getattr(args, "gen_min_len", 15)
    args.length_penalty = getattr(args, "length_penalty", 2.0)
    args.eval_interval = getattr(args, "eval_interval", 400)
    args.save_interval = getattr(args, "save_interval", 4000)
    args.num_beams = getattr(args, "num_beams", 4)
    args.project_name = getattr(args, "project_name", "bart (simcas wcep)")
    args.desc = getattr(args, 'desc', '')
    args.is_wandb = getattr(args, 'is_wandb', False)


def arxiv_setting(args):
    args.batch_size = getattr(args, 'batch_size', 1)
    args.epoch = getattr(args, 'epoch', 100)
    args.report_freq = getattr(args, "report_freq", 50)
    args.accumulate_step = getattr(args, "accumulate_step", 8)
    args.pretrained = getattr(args, "pretrained", None)
    args.model_type = getattr(args, "model_type", "/apdcephfs_qy3/share_1565115/jonxie/model_base/bart-base")
    args.dataset_name = getattr(args, "dataset_name", "/apdcephfs_qy3/share_1565115/jonxie/data_base/SimCAS/arxiv_bart_512")
    args.warmup_steps = getattr(args, "warmup_steps", 10000)
    args.grad_norm = getattr(args, "grad_norm", 0)
    args.seed = getattr(args, "seed", 5555)
    args.max_lr = getattr(args, "max_lr", 1e-2)
    args.max_len = getattr(args, "max_len", 128)
    args.smooth = getattr(args, "smooth", 0.1)
    args.max_input_len = getattr(args, 'max_input_len', 16384)
    args.max_output_len = getattr(args, 'max_output_len', 1024)
    args.chunk_len = getattr(args, 'chunk_len', 512)
    args.gen_max_len = getattr(args, "gen_max_len", 300)
    args.gen_min_len = getattr(args, "gen_min_len", 50)
    args.length_penalty = getattr(args, "length_penalty", 5.0)
    args.eval_interval = getattr(args, "eval_interval", 1000)
    args.save_interval = getattr(args, "save_interval", 10000)
    args.num_beams = getattr(args, "num_beams", 4)
    args.project_name = getattr(args, "project_name", "bart (simcas arxiv)")
    args.desc = getattr(args, 'desc', '')
    args.is_wandb = getattr(args, 'is_wandb', False)

def pubmed_setting(args):
    args.batch_size = getattr(args, 'batch_size', 1)
    args.epoch = getattr(args, 'epoch', 100)
    args.report_freq = getattr(args, "report_freq", 50)
    args.accumulate_step = getattr(args, "accumulate_step", 16)
    args.pretrained = getattr(args, "pretrained", None)
    args.model_type = getattr(args, "model_type", "/apdcephfs_qy3/share_1565115/jonxie/model_base/bart-base")
    args.dataset_name = getattr(args, "dataset_name", "/apdcephfs_qy3/share_1565115/jonxie/data_base/SimCAS/pubmed_bart_512")
    args.warmup_steps = getattr(args, "warmup_steps", 10000)
    args.grad_norm = getattr(args, "grad_norm", 0)
    args.seed = getattr(args, "seed", 555)
    args.max_lr = getattr(args, "max_lr", 1e-2)
    args.max_len = getattr(args, "max_len", 128)
    args.smooth = getattr(args, "smooth", 0.1)
    args.max_input_len = getattr(args, 'max_input_len', 16384)
    args.max_output_len = getattr(args, 'max_output_len', 1024)
    args.chunk_len = getattr(args, 'chunk_len', 512)
    args.gen_max_len = getattr(args, "gen_max_len", 400)
    args.gen_min_len = getattr(args, "gen_min_len", 40)
    args.length_penalty = getattr(args, "length_penalty", 4.0)
    args.eval_interval = getattr(args, "eval_interval", 1000)
    args.save_interval = getattr(args, "save_interval", 10000)
    args.num_beams = getattr(args, "num_beams", 4)
    args.project_name = getattr(args, "project_name", "bart (simcas pubmed)")
    args.desc = getattr(args, 'desc', '')
    args.is_wandb = getattr(args, 'is_wandb', False)


def govreport_setting(args):
    args.batch_size = getattr(args, 'batch_size', 1)
    args.epoch = getattr(args, 'epoch', 100)
    args.report_freq = getattr(args, "report_freq", 50)
    args.accumulate_step = getattr(args, "accumulate_step", 8)
    args.pretrained = getattr(args, "pretrained", None)
    args.model_type = getattr(args, "model_type", "/apdcephfs_qy3/share_1565115/jonxie/model_base/bart-base")
    args.dataset_name = getattr(args, "dataset_name", "/apdcephfs_qy3/share_1565115/jonxie/data_base/SimCAS/govreport_bart_512")
    args.warmup_steps = getattr(args, "warmup_steps", 1600)
    args.grad_norm = getattr(args, "grad_norm", 0)
    args.seed = getattr(args, "seed", 777)
    args.max_lr = getattr(args, "max_lr", 4e-3)
    args.max_len = getattr(args, "max_len", 128)
    args.smooth = getattr(args, "smooth", 0.1)
    args.max_input_len = getattr(args, 'max_input_len', 16384)
    args.max_output_len = getattr(args, 'max_output_len', 1024)
    args.chunk_len = getattr(args, 'chunk_len', 512)
    args.gen_max_len = getattr(args, "gen_max_len", 740)
    args.gen_min_len = getattr(args, "gen_min_len", 50)
    args.length_penalty = getattr(args, "length_penalty", 2.0)
    args.eval_interval = getattr(args, "eval_interval", 500)
    args.save_interval = getattr(args, "save_interval", 10000)
    args.num_beams = getattr(args, "num_beams", 4)
    args.project_name = getattr(args, "project_name", "")
    args.desc = getattr(args, 'desc', 'TODO')
    args.is_wandb = getattr(args, 'is_wandb', False)


def summscreen_setting(args):
    args.batch_size = getattr(args, 'batch_size', 1)
    args.epoch = getattr(args, 'epoch', 100)
    args.report_freq = getattr(args, "report_freq", 50)
    args.accumulate_step = getattr(args, "accumulate_step", 8)
    args.pretrained = getattr(args, "pretrained", None)
    args.model_type = getattr(args, "model_type", "/apdcephfs_qy3/share_1565115/jonxie/model_base/bart-base")
    args.dataset_name = getattr(args, "dataset_name", "/apdcephfs_qy3/share_1565115/jonxie/data_base/SimCAS/summscreen_bart_512")
    args.warmup_steps = getattr(args, "warmup_steps", 6400)
    args.grad_norm = getattr(args, "grad_norm", 0)
    args.seed = getattr(args, "seed", 777)
    args.max_lr = getattr(args, "max_lr", 8e-3)
    args.max_len = getattr(args, "max_len", 128)
    args.smooth = getattr(args, "smooth", 0.1)
    args.max_input_len = getattr(args, 'max_input_len', 16384)
    args.max_output_len = getattr(args, 'max_output_len', 1024)
    args.chunk_len = getattr(args, 'chunk_len', 512)
    args.gen_max_len = getattr(args, "gen_max_len",750)
    args.gen_min_len = getattr(args, "gen_min_len", 50)
    args.length_penalty = getattr(args, "length_penalty", 4.0)
    args.eval_interval = getattr(args, "eval_interval", 1000)
    args.save_interval = getattr(args, "save_interval", 10000)
    args.num_beams = getattr(args, "num_beams", 4)
    args.project_name = getattr(args, "project_name", "")
    args.desc = getattr(args, 'desc', 'TODO')
    args.is_wandb = getattr(args, 'is_wandb', False)


def nrtv_setting(args):
    args.batch_size = getattr(args, 'batch_size', 1)
    args.epoch = getattr(args, 'epoch', 100)
    args.report_freq = getattr(args, "report_freq", 50)
    args.accumulate_step = getattr(args, "accumulate_step", 4)
    args.pretrained = getattr(args, "pretrained", None)
    args.model_type = getattr(args, "model_type", "/apdcephfs_qy3/share_1565115/jonxie/model_base/bart-base")
    args.dataset_name = getattr(args, "dataset_name", "/apdcephfs_qy3/share_1565115/jonxie/data_base/SimCAS/nrtv_bart_512")
    args.warmup_steps = getattr(args, "warmup_steps", 1600)
    args.grad_norm = getattr(args, "grad_norm", 0)
    args.seed = getattr(args, "seed", 777)
    args.max_lr = getattr(args, "max_lr", 4e-3)
    args.max_len = getattr(args, "max_len", 128)
    args.smooth = getattr(args, "smooth", 0.1)
    args.max_input_len = getattr(args, 'max_input_len', 16384)
    args.max_output_len = getattr(args, 'max_output_len', 1024)
    args.chunk_len = getattr(args, 'chunk_len', 512)
    args.gen_max_len = getattr(args, "gen_max_len", 20)
    args.gen_min_len = getattr(args, "gen_min_len", 1)
    args.length_penalty = getattr(args, "length_penalty", 3.0)
    args.eval_interval = getattr(args, "eval_interval", 1000)
    args.save_interval = getattr(args, "save_interval", 10000)
    args.num_beams = getattr(args, "num_beams", 4)
    args.project_name = getattr(args, "project_name", "")
    args.desc = getattr(args, 'desc', 'TODO')
    args.is_wandb = getattr(args, 'is_wandb', False)
   